### ISSUE TITLE
mainnet indexer failing with "missing field `metadata`"

### ISSUE THREAD

**Issue by damian0815** [tzConnectBerlin/que-pasa#49]
Since last night I'm getting this error trying to index mainnet: 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: failed to get json for block 2125355

Caused by:
    0: failed to deserialize block json
    1: missing field `metadata` at line 1 column 1223
```

it coincided with messages about new versions of Octez i got through the dev slack - so perhaps something has changed on the mainnet node sides, and the json format expected by que-pasa is no longer correct? i think it's related to `block.rs` line 722 expecting `pub metadata: OperationMetadata`, but inspecting `curl https://mainnet-tezos.giganode.io/chains/main/blocks/2125355 | less` there's indeed no field `metadata` in the returned json.

**Comment by damian0815** [comment]
@RKlompUU any idea what's going on here? the EndlessWays.net frontend is currently broken because of this issue :/

**Comment by RKlompUU** [comment]
This sounds like the public node you're using doesn't provide full historic data (it's not an archive node). Because only archive nodes provide this "metadata" field, which que pasa needs. This error message is exactly what you'd get when trying to index using a non-archive node.

Have you already tried using another (public) node?

I can look further into it but in principal am off  until Monday. Let me know if you need urgent further help, if so I'll come online properly and see what I can do then.

**Comment by damian0815** [comment]
@RKlompUU i haven't changed the node i'm using, i'll try using others and see if that solves it. don't worry about it before monday either way.

**Comment by damian0815** [comment]
according to the tezos dev slack this is a known octez problem, not a que-pasa problem. will hopefully be fixed next week.

**Comment by RKlompUU** [comment]
@damian0815 I just learned that we (at TZConnect) have a mainnet archive node that is up and healthy (and fortunately it's on the only version, v12.0, that both works for the latest protocol upgrade as well as is not affected by this recent "metadata" field bug in Octez).

You may use this node! https://mainnet-archive.tzconnect.berlin

**Comment by damian0815** [comment]
oh, thanks!
